### ISSUE TITLE
RIO detection codes

### ISSUE THREAD

**Issue by SaraDadjouy** [sbasu276/GBCNet#2]
Hi, I was looking at the code and realized that you imported the predicted ROIs at the beginning of the train.py and test.py. Does this mean that these codes don't detect the ROIs? If I want to use this code, should I import raw images or images with ROIs?

**Comment by sbasu276** [comment]
For this model, you need to pass the images with candidate ROIs as available in the `roi_pred.json` file. 
I updated README with the link to code and model weight of the ROI detector. In case you want to re-run the first stage (ROI detection), you need to run that, store the predicted ROIs, and pass them to the code of this repo (classifier).

**Comment by SaraDadjouy** [comment]
> For this model, you need to pass the images with candidate ROIs as available in the `roi_pred.json` file. I updated README with the link to code and model weight of the ROI detector. In case you want to re-run the first stage (ROI detection), you need to run that, store the predicted ROIs, and pass them to the code of this repo (classifier).

Thank you so much for your help with my question.
