### ISSUE TITLE
Clarification on Image-Patient Correspondence in GBCU Dataset

### ISSUE THREAD

**Issue by SaraDadjouy** [sbasu276/GBCNet#3]
Hello,
I hope you’re doing well. I’m currently exploring the GBCU dataset and it seems like it’s not clear which image belongs to which patient. I was wondering if you could help me with that.

**Comment by Ghost0405** [comment]
Hi, I'm sorry to bother you, but I wanted to ask how long it took you from the time you applied to the GBC US dataset to the time two professors responded to you ?

**Comment by SaraDadjouy** [comment]
@Ghost0405 
Hi, the application for the dataset was managed by my supervisor. Unfortunately, I don't have detailed insights into the process.

**Comment by Ghost0405** [comment]
> @Ghost0405 Hi, the application for the dataset was managed by my supervisor. Unfortunately, I don't have detailed insights into the process.

@SaraDadjouy 
I am glad to see your reply, may I ask which professor is your supervisor? My supervisor and I are very interested in these work, please can you leave a contact information of your supervisor as well as you, through the contact information can increase the possibility for us to have a collaborative exchange.
